### ISSUE TITLE
Dashboard templating

### ISSUE THREAD

**Issue by bubu11e** [ovh/ovh-warp10-datasource#11]
Hi,
When using warp10 query for templating purpose, the value of the var is the position of the element in the stack for the second element to the last one. I use grafana v4.
Regards,

[dashboard.txt](https://github.com/cityzendata/grafana-warp10/files/750460/dashboard.txt)

**Comment by LostInBrittany** [comment]
Thanks for the issue, I will look at it this week

**Comment by miton18** [comment]
Grafana use struct with text and value for each result (each entry of the stack).
With #14  value is the content of the entry and text is a toString() of the entry (for strings and numbers) else setted to the indice of the stack. this seems to solve your issue

**Comment by LostInBrittany** [comment]
It seems the PR solved the issue, if you still have a problem, please reopen :)
