### ISSUE TITLE
Authentication token should be per datasource

### ISSUE THREAD

**Issue by rledisez** [ovh/ovh-warp10-datasource#12]
The token used to authenticate against warp endpoint should be defined at the datasource level to avoid writing it in every warpscript. Because, if the token change, it would be very annoying to edit the tens/hundreds of scripts just to update the token.

The datasource should replace a well defined string in the warp script by the token.

Eg:

WARP script:
[ $warp_ds_token '=my.timeserie' { 'tag' 1 } $end $interval ] FETCH 'gts' STORE

The datasource would replace $warp_ds_token by the token.

It seems it could be easy to do in datasource.js, function metricFindQuery().

**Comment by rledisez** [comment]
It could be even more generic. A "WARP Script preambule" textarea where the user can type some warp script that woulds be inserted on top of each script before being sent to API endpoint. That's because I see that all my script start with the same lines of code. I don't know if it should be inserted before or after template variables (i would prefer after for my use cases but that might be more complicated). Example:
```
'****' 'warp_auth_token' STORE
300 'step' STORE
<% $template_variable 'None' == %>
    <% STOP %>
    IFT
```

**Comment by bubu11e** [comment]
Hi,

I don't think adding the token at the data source level would be such a good idea. I manage hundreds of tokens and don't imagine defining hundreds of data sources.

If all of you're grafana's warpscripts start with the same header, why don't you define a macro that you place in the file ${WARP10_HOME}/macros/grafana/header.mc2 with the content:

    <%
    '****' 'warp_auth_token' STORE
    300 'step' STORE
    <% $template_variable 'None' == %>
    <% STOP %>
    IFT
    %>

And then call the macro in you're dasboards using:

    @grafana/header

That way, any changes made in the macro would be propagated into all you're dashboards. In addition, you can call this macro in any other tool.

Best regards,

**Comment by rledisez** [comment]
I exactly need ${WARP10_HOME}/macros/grafana/header.mc2, but in Grafana :)

I don't have access the the Grafana or Warp10 servers, because it's a shared deployment. I only have an admin access to an organization. That's why defining macros at the datasource level seems appropriate.

**Comment by bubu11e** [comment]
Macros are an important part of Warp10.

On our production platform I authorized every user to have a git repository which is synchronized every minute on the egress server in a sub directory of ${WARP10_HOME}/macros.

This is not perfect but that allow every user to manage their own macros without giving them access to the server (the perfect solution would be to use a continuous integration tool to check code an submit the synchronization).

Can't you propose a similar solution to you're Warp10 administrator ?

That would be much more flexible for you.

Regards,

**Comment by LostInBrittany** [comment]
Thanks for the issue, @rledisez. I understand what you mean, putting the token in the warpscript is definitively not the best way to do things.
 
I agree with @julien-girard . Many of our users have hundreds, even thousands, of tokens, so defining a datasource by token is not the way we prefer to tackle your problem. His suggestion of using macros fits well with the spirit of Warp 10.

**Comment by cityzendata** [comment]
Problem could be solved if Grafana allowed you to define a global 'map'
with simple key to value mappings, the Warp 10 plugin could dereference
elements of this map and include them in the script, for example if the
global map was named foo we could support things like

%%foo.key%% which would be replaced by the value associated with 'key' in
the map 'foo' in the script prior to sending it to Warp 10.


On Sun, Feb 12, 2017 at 10:34 PM, Horacio Gonzalez <notifications@github.com

**Comment by LostInBrittany** [comment]
That global map would be something like a config file, and the plugin could directly load it.

Another way of doing that, more fitting with Grafana, could be defining that map in the Datasource.
The plugin could look for a config map in the datasource and if it's there it could use it. This method would keep existing install working as it (no config, no action) and allowing the configuration of any number of tokens directly in the datasource if wanted.

I'm going to try to propose a working example of this solution this week

**Comment by miton18** [comment]
Some update:
A map (key/value) injected on the top of your WarpScript is now available at datasource level.

**Comment by miton18** [comment]
This issue seems inactive, closing it.
You can create a new one if you still have this issue.
