### ISSUE TITLE
Panel & Row repeats

### ISSUE THREAD

**Issue by rledisez** [ovh/ovh-warp10-datasource#13]
Given a dashboard with the following template variable:
* name: foo
* type: custom
* values: 1,2
* multi-value: true

When enabling panel repeat (or row repeat, same issue), the requests generated to fetch the data are invalid if there is multiple values selected (which is the point of the repeating option).

Expected:
If the two values of foo are selected, two requests must be generated.
- first one should contain `1 'foo' STORE`
- second one should contain `2 'foo' STORE`

Observed:
Two requests are generated, both with `'1 + 2' 'foo' STORE`

It works fine with OpenTSDB datasource, so I guess it's a datasource issue.

**Comment by LostInBrittany** [comment]
Thanks for the issue!

I will look at it this week.

**Comment by miton18** [comment]
This issue seems inactive, closing it.
You can create a new one if you still have this issue.
