### ISSUE TITLE
interval variable semantic

### ISSUE THREAD

**Issue by tgermain** [ovh/ovh-warp10-datasource#16]
Hi, 

according to grafana doc http://docs.grafana.org/reference/templating/#the-interval-variable the `$__interval` variable is a great as the bucket size parameter. That how it is used for influxdb and elasctisearch data sources.

but in warp, there is a variable `interval` injected into the warpscript but its equal to the current time range (if I select "last 3 hours' as a time range, `interval=3h`). So if I use it as the bucket size parameter, it yeld only 1 data point for the whole time range.

**Comment by miton18** [comment]
Hi @tgermain, you have now the 2 variables available in your scripts: **$interval** and **$__interval**
