### ISSUE TITLE
editor.js 404 Not Found behind nginx reverse proxy

### ISSUE THREAD

**Issue by Nicolou** [ovh/ovh-warp10-datasource#18]
Hello,

I Don't know if this issue concerns Grafana Team or Cityzendata.
I follow the doc : http://docs.grafana.org/installation/behind_proxy/
So, when I use warp10 plugin behind nginx revers proxy, the **editor.js** is not available because the url is not rewriting with '/grafana/' as configured in nginx before the domain name.

> Unhandled promise rejection 
> Error: Fetch error: 404 Not Found
>   Instantiating http://myUrl.fr/public/plugins/grafana-warp10-datasource/editor.js
>   Loading /public/plugins/grafana-warp10-datasource/editor.js

good url is : http://myUrl.fr/grafana/public/plugins/grafana-warp10-datasource/editor.js

All others functionality of warp10 plug-in  work fine.
Please, could you check if 'root_url' configuration variable is supported ?

thank you

Here my confs :
[grafana.conf.txt](https://github.com/cityzendata/grafana-warp10/files/1777372/grafana.conf.txt)
[nginx.conf.txt](https://github.com/cityzendata/grafana-warp10/files/1777361/nginx.conf.txt)

**Comment by miton18** [comment]
Hi @Nicolou, #23 remove some hard coded links to Ace editor related dependancies.
Can you test ?

**Comment by Nicolou** [comment]
Hi,
It works !
Thank you
