### ISSUE TITLE
JS error with Firefox res.data.map is not a function

### ISSUE THREAD

**Issue by Nohzoh** [ovh/ovh-warp10-datasource#34]
There is a javascript error when displaying dashboard:
![image](https://user-images.githubusercontent.com/38663853/54297957-27783880-45b8-11e9-8e39-d7a737e5627d.png)

The problem is certainly there:
https://github.com/ovh/ovh-warp10-datasource/blob/master/src/warp10-datasource.ts#L194

**Comment by miton18** [comment]
Can you tell me which version of Firefox ?

**Comment by Nohzoh** [comment]
Can't reproduce the problem anymore
