### ISSUE TITLE
CLA is incorrect

### ISSUE THREAD

**Issue by hbs** [ovh/ovh-warp10-datasource#42]
The CLA for this project mentions projects made available by SAP which seems incorrect.

https://cla-assistant.io/ovh/ovh-warp10-datasource?pullRequest=41

Before this is fixed the CLA cannot be signed.

If it has been signed prior to this issue being fixed, then we can conclude the signing party did not read it!

**Comment by miton18** [comment]
Thanks ! We just update it, good catch !
