### ISSUE TITLE
Error while managing Warp10 datasource with Grafana 6.4.1

### ISSUE THREAD

**Issue by Nohzoh** [ovh/ovh-warp10-datasource#45]
With a fresh install of Grafana (6.4.1), the warp10 datasource rises an error when accessing to the creation form:
```
Error: ace is not defined Evaluating https://.../public/plugins/ovh-warp10-datasource/warp10-query.controller.js Evaluating https://.../public/plugins/ovh-warp10-datasource/module.js Loading plugins/ovh-warp10-datasource/module
Data Source Error
```

![image](https://user-images.githubusercontent.com/38663853/66206817-7b13b600-e6b1-11e9-94b4-9de623b575de.png)

**Comment by ghost** [comment]
Same error using a hosted grafana (by grafana.com). Their rolling update in 6.4.3 has created the same problem. All our dashboards are down. They are providing the Grafana Warp10 Datasource Plugin 2.1.1.

**Comment by FGRibreau** [comment]
Same with Grafana v6.4.3 (commit: 3a2bfb7). 
It seems to be related with https://github.com/grafana/grafana/issues/19982 

> Yes, sorry about this. Since the change to loading ace async required no change to internal data sources we did not check external ones.

cc @LostInBrittany

**Comment by miton18** [comment]
Fixed by #44, enhanced by #46 

Now, we need to make a release on plugin registry

**Comment by FGRibreau** [comment]
@miton18 great! can't wait :)

**Comment by leoncx** [comment]
@miton18 Thanks, I will test as soon as it is available.

**Comment by jlannoy** [comment]
Hello. Do you have any release date for this fix please?

**Comment by FGRibreau** [comment]
Same question here :)

**Comment by loicguillois** [comment]
interested too

**Comment by StevenLeRoux** [comment]
We will release it in just a few days and will keep you informed on this issue.

**Comment by miton18** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/559 PR done

**Comment by Nohzoh** [comment]
The problem is fixed
Thank you
