### ISSUE TITLE
Error when adding query in Templating

### ISSUE THREAD

**Issue by TomEros** [ovh/ovh-warp10-datasource#5]
When adding a query in templating we have this error : 

```
Templating
Template variables could not be initialized: b.metricFindQuery is not a function
```

**Comment by miton18** [comment]
#6  I try something...

**Comment by LostInBrittany** [comment]
@TomEros I've merged the PR proposed by @miton18 , can you tell me if it solves your problem?

**Comment by TomEros** [comment]
Perfect ! It solves the problem 
Thx
