### ISSUE TITLE
Multiple and All values are send as 'value1 + value2 + …'

### ISSUE THREAD

**Issue by tduboys** [ovh/ovh-warp10-datasource#57]
Hi,

When using multiple values or All options (with auto mode), the query sent to the Warp10 datasource is like that : 
`'value1 + value2 + value3 + …' variable STORE`

Warp10 didnt like it. A best way will be to send something like : 
`'~(value1|value2|value3|…)' variable STORE`

With All option, I can override with a custom value of '~.*' but it does not work with multiple option.

**Comment by pi-r-p** [comment]
A more general implementation will be to store a list of strings. `[ 'value1' 'value2' 'value3' ] 'var' STORE` . This way you can handle it the way you want, even for more complex use cases than a FETCH.
I can't find out where does Grafana does this in their source code...

For your case, building a regexp will be as simple as this
`'~' $var REOPTALT +` 

[Grafana wrote here about this problem,](https://grafana.com/docs/grafana/latest/reference/templating/#formatting-multiple-values) but there is no doc.

**Comment by tduboys** [comment]
I read that the formatting of multiple/all values is made by the datastore, it's why I created the issue here and not in Grafana directly.
For example, in the MySQL datastore, there is some code like that : https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/mysql/datasource.ts#L34

But I dont know this language, it's hard for me to make a PR :)

**Comment by pi-r-p** [comment]
@tduboys : It took me a while to dive intro Grafana source code, but this will soon be fixed. See #59

**Comment by tduboys** [comment]
> @tduboys : It took me a while to dive intro Grafana source code, but this will soon be fixed. See #59

Yes, I'm following it :) thanks !
