### ISSUE TITLE
Firefox N/A everywhere

### ISSUE THREAD

**Issue by Nohzoh** [ovh/ovh-warp10-datasource#69]
With Firefox 75 (last version available), requests seems to always fail.
When I look in dev tools network information, I can see that Firefox does not see data as it should.
When I try to copy the request from dev tools as curl command and executes it from a terminal, it works fine.

With Firefox 75:
![image](https://user-images.githubusercontent.com/38663853/80943362-50284680-8de7-11ea-935e-df9a821b0ddb.png)

With Chrome:
![image](https://user-images.githubusercontent.com/38663853/80943421-7352f600-8de7-11ea-9ac4-92afc1a58b9d.png)

I use charts and singlestats panels and I get this issue with both.

**Comment by miton18** [comment]
The last time I see this things it was an encoding, issue, an error on GZip headers, can you look at them ?

**Comment by Nohzoh** [comment]
All seems good.
I don't see any error.
![image](https://user-images.githubusercontent.com/38663853/80960540-5d562d00-8e09-11ea-8be7-2c71909e0ecb.png)

I wrote the raw result to a file and checked it, it is a gzip of the expected content

**Comment by Nohzoh** [comment]
in fact it is the same issue than #65 
the grafana proxy mode adds a content-type to warp10 response
